---
archives:
  - format_overrides:
      - goos: windows
        format: zip
before:
  hooks:
    - go mod tidy
builds:
  - binary: jaguarsd
    main: ./cmd/jaguarsd/main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - darwin
      - linux
      - windows
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
